server:
  port: 8011

spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: 'localhost'
      port: 8500
feign:
  client:
    config:
      default:
        connect-timeout: 500
        read-timeout: 500
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
resilience4j:
  circuitbreaker: #断路器
    backends:
      menu:  #menu 熔断器
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        ring-buffer-size-in-closed-state: 5
        ring-buffer-size-in-half-open-state: 3
        wait-duration-in-open-state: 5000
      order: #order 熔断器
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        ring-buffer-size-in-closed-state: 5
        ring-buffer-size-in-half-open-state: 3
        wait-duration-in-open-state: 5000
  #限流控制
  bulkhead:
    backends:
      menu:
        max-concurrent-call: 5 #最多5个线程
        max-wait-time: 5  #最多等待5s
      order:
        max-concurrent-call: 1
        max-wait-time: 5
