server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 'localhost:8848'