server:
  port: 8888

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: 'localhost'
      port: 8500
    config:
      server:
        git:
          #          uri: https://github.com/h-dj/SpringCloud-Learning/     # 配置git仓库的地址
          #          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          #          username:                                              # git仓库的账号
          #          password:
          uri: file:///home/hdj/IdeaProjects/config-repo