server:
  port: 8989

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: 'localhost'
      port: 8500

order:
  discount: 90