server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always

spring:
  cloud:
    zookeeper:
      connect-string: 'localhost:2181'