server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always

spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: 'localhost'
      port: 8500