server:
  port: 8002
spring:
  application:
    name: spring-cloud-eureka
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/,http://peer3:8002/eureka/